Tu 29 implement e slint and prettier
TeamUp3Batch/yummydash-backend pull request #14
Opened 2023-10-14 09:40 UTC by kavithashanmugan

eslint and prettier was installed along with adding new api - getRestaurantDetailsById

added phoneNumber for signUp process

2023-10-14 17:00 UTC, DJCrossman requested changes

2023-10-14 17:00 UTC, DJCrossman commented on routes/usersRoutes.js
> +// const protect = require('../middleware/authMiddleware');
Remove unused code.

2023-10-16 18:03 UTC, kavithashanmugan commented on config/db.js
> +    console.log('hello');
i have replaced console.log with logger

2023-10-16 18:04 UTC, kavithashanmugan commented on controllers/authController.js
> +  console.log('email and password', req.body.email, req.body.password);
i have removed the console for passowrd

2023-10-16 18:14 UTC, DJCrossman approved these changes

2023-10-16 22:32 UTC, anithaamarnath approved these changes

2023-10-16 22:32 UTC, TeamUp3Batch approved these changes

2023-10-18 18:22 UTC, merged